version: 5.1.0
variant: default
logo: /img/logo.svg
head:
  favicon: /img/favicon.svg
  manifest:
    name:
    short_name:
    start_url:
    theme_color:
    background_color:
    display: standalone
    icons:
      - src: ""
        sizes: ""
        type:
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    publisher:
    publisher_logo:
    image:
  meta:
    - ""
  rss:
navbar:
  menu:
    首页: /
    归档: /archives/
    分类: /categories/
    标签: /tags/
    关于: /about/
  links:
    Download on GitHub:
      icon: fab fa-github
      url: https://github.com/ppoffice/hexo-theme-icarus
footer:
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Download on GitHub:
      icon: fab fa-github
      url: https://github.com/ppoffice/hexo-theme-icarus
article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: unfolded
  readtime: true
  update_time: true
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
search:
  type: insight
comment:
  type: changyan
  app_id: cyvMpzrs2
  conf: prod_b46a8c1e9f659c7176ab10438fbfdf31
donates:
  - type: alipay
    qrcode: photos/images/支付宝收款码.jpg
  - type: buymeacoffee
    url: https://www.buymeacoffee.com/ddabb
  - type: patreon
    url: https://www.patreon.com/ddabb
  - type: wechat
    qrcode: photos/images/微信收款码.jpg
sidebar:
  left:
    sticky: false
  right:
    sticky: false
widgets:
  - position: right
    type: profile
    author: 十六
    author_title: 程序员
    location: 长沙,深圳
    avatar:
    avatar_rounded: false
    gravatar:
    follow_link: https://github.com/ddabb
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/ddabb
  - position: right
    type: toc
    index: true
    collapsed: true
    depth: 3
  - position: right
    type: links
    links:
      网站源码: https://github.com/ddabb/hexo_ci
      FreeToKnow: https://github.com/ddabb/FreeToKnow
      百家号: https://baijiahao.baidu.com/u?app_id=1618115111689564
      知乎: https://www.zhihu.com/people/60points
      今日头条: https://www.toutiao.com/c/user/token/MS4wLjABAAAAeVT3k75rtRi9XJfGmmRa0DoM6b_dwXbHu4fDL9r0RL9LGqAVMh7puZ0EFcsQ3QbT
      自助台球管家: https://www.60score.com/
  - position: right
    type: categories
  - position: right
    type: recent_posts
  - position: right
    type: archives
  - position: right
    type: tags
  - position: right
    type: subscribe_email
    description:
    feedburner_id: ""
  - position: right
    type: followit
    description:
    action_url: ""
    verification_code: ""
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
    tracking_id: 087f6d1aba6061dea2ecf6d386ea7651
  bing_webmaster:
    tracking_id:
  busuanzi: true
  cnzz:
    id:
    web_id:
  cookie_consent:
    type: info
    theme: edgeless
    static: false
    position: bottom-left
    policyLink: https://www.cookiesandyou.com/
  gallery: true
  google_analytics:
    tracking_id:
  hotjar:
    site_id:
  katex: true
  mathjax: true
  outdated_browser: false
  progressbar: true
  statcounter:
    project:
    security:
  twitter_conversion_tracking:
    pixel_id:
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
